### ISSUE TITLE
Finisher typo in `Breadlesscode.Commentable:From.Finisher.AddComment.Definition`

### ISSUE THREAD

**Issue by jobee** [breadlesscode/neos-commentable#2]
Hey,
looking at your package I noticed a typo... `From.Finisher...` should be `Form.Finisher...` I guess.
I'm not using you package currently, so I won't be able to provide a PR, just wanted to let you know.

I'm also not sure, when its the right time to fix this, probably a new major should be released, as this change would be breaking.

**Comment by breadlesscode** [comment]
Thank you, should be fixed in next release :+1:
